service: HLSstream

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

# The `functions` block defines what code to deploy
functions:
  streaming:
    handler: handler.stream
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: HLS-stream
          method: get
          cors: true
